kind: Pod
apiVersion: v1beta3
#metadata:
  #name: tbfe
  #labels: 
    #name: tbfe
#spec:
  #ports:
    #- port: 80
    #targetPort: 8080
    #protocol: TCP
  #selector:
    #name: tbfe

id: tbfe
desiredState:
  manifest:
    version: v1beta1
    id: tbfe
    containers:
      - name: tbfe
        image: gcr.io/radiant-cloud/tbfe
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: yourpassword
        cpu: 100
        ports:
          - containerPort: 80
labels:
  name: tbfe
