kind: Service
apiVersion: v1beta3
id: tbfe

metadata: 
  name: tbfe-frontend
  labels: 
    name: tbfe-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: tbfe

